FROM artifactory.app.local/kube-public/java21_azul_debian_base_image:21.0.6-1
WORKDIR /
ARG JAR_FILE=target/generate-order.jar
COPY ${JAR_FILE} /generate-order.jar

ENV LANG ru_RU.UTF-8
ENV LC_ALL=ru_RU.UTF-8
ENV LANGUAGE=ru_RU.UTF-8

CMD ["java","-jar","generate-order.jar"]
